import * as fs from 'node:fs';
import * as path from 'node:path';
import { removeInstrumentedCopy, writeInstrumentedCopy } from '../src/instrument';

const UUID_PATTERN = '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}';

describe('writeInstrumentedCopy / removeInstrumentedCopy — G2 (Gap 2)', () => {
  const fixturePath = path.join(__dirname, 'fixtures', 'g2', 'workflow-with-import.ts');
  let writtenPaths: string[] = [];

  afterEach(() => {
    for (const p of writtenPaths) {
      removeInstrumentedCopy(p);
    }
    writtenPaths = [];
  });

  it('writes a sibling file in the same directory as the original', () => {
    const instrumentedPath = writeInstrumentedCopy(fixturePath, 'usesHelper');
    writtenPaths.push(instrumentedPath);

    expect(path.dirname(instrumentedPath)).toBe(path.dirname(fixturePath));
    expect(fs.existsSync(instrumentedPath)).toBe(true);
  });

  it('names the file <sourceName>.<functionName>.<uuid>.pathkit-instrumented.ts', () => {
    const instrumentedPath = writeInstrumentedCopy(fixturePath, 'usesHelper');
    writtenPaths.push(instrumentedPath);

    const fileName = path.basename(instrumentedPath);
    const expectedPattern = new RegExp(`^workflow-with-import\\.usesHelper\\.${UUID_PATTERN}\\.pathkit-instrumented\\.ts$`);
    expect(fileName).toMatch(expectedPattern);
  });

  it('is byte-identical to the original modulo a generated-file banner comment', () => {
    const instrumentedPath = writeInstrumentedCopy(fixturePath, 'usesHelper');
    writtenPaths.push(instrumentedPath);

    const originalText = fs.readFileSync(fixturePath, 'utf8');
    const instrumentedText = fs.readFileSync(instrumentedPath, 'utf8');

    expect(instrumentedText.endsWith(originalText)).toBe(true);
    expect(instrumentedText.length).toBeGreaterThan(originalText.length);
    expect(instrumentedText).toMatch(/^\/\/ AUTO-GENERATED by pathkit coverage/);
  });

  it('preserves the relative import to a sibling helper module unchanged', () => {
    const instrumentedPath = writeInstrumentedCopy(fixturePath, 'usesHelper');
    writtenPaths.push(instrumentedPath);

    const instrumentedText = fs.readFileSync(instrumentedPath, 'utf8');
    expect(instrumentedText).toContain("from './helper'");
  });

  it('calling it twice in a row produces two distinct, non-colliding filenames', () => {
    const first = writeInstrumentedCopy(fixturePath, 'usesHelper');
    const second = writeInstrumentedCopy(fixturePath, 'usesHelper');
    writtenPaths.push(first, second);

    expect(first).not.toBe(second);
    expect(fs.existsSync(first)).toBe(true);
    expect(fs.existsSync(second)).toBe(true);
  });

  it('throws a PathKitError when the workflow file does not exist', () => {
    const missingPath = path.join(__dirname, 'fixtures', 'g2', 'does-not-exist.ts');
    expect(() => writeInstrumentedCopy(missingPath, 'whatever')).toThrow(/not found/i);
  });

  it('removeInstrumentedCopy deletes the file and does not throw if called again on an already-deleted path', () => {
    const instrumentedPath = writeInstrumentedCopy(fixturePath, 'usesHelper');
    removeInstrumentedCopy(instrumentedPath);
    expect(fs.existsSync(instrumentedPath)).toBe(false);
    expect(() => removeInstrumentedCopy(instrumentedPath)).not.toThrow();
  });
});
