import * as fs from 'node:fs';
import * as path from 'node:path';
import { prepareCoverageRun, removeInstrumentedCopy, writeInstrumentedCopy } from '../src/instrument';

const UUID_PATTERN = '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}';

describe('writeInstrumentedCopy / removeInstrumentedCopy — G2 (Gap 2)', () => {
  const fixturePath = path.join(__dirname, 'fixtures', 'g2', 'workflow-with-import.ts');
  let writtenPaths: string[] = [];

  afterEach(() => {
    for (const p of writtenPaths) {
      removeInstrumentedCopy(p);
    }
    writtenPaths = [];
  });

  it('writes a sibling file in the same directory as the original', () => {
    const instrumentedPath = writeInstrumentedCopy(fixturePath, 'usesHelper');
    writtenPaths.push(instrumentedPath);

    expect(path.dirname(instrumentedPath)).toBe(path.dirname(fixturePath));
    expect(fs.existsSync(instrumentedPath)).toBe(true);
  });

  it('names the file <sourceName>.<functionName>.<uuid>.pathkit-instrumented.ts', () => {
    const instrumentedPath = writeInstrumentedCopy(fixturePath, 'usesHelper');
    writtenPaths.push(instrumentedPath);

    const fileName = path.basename(instrumentedPath);
    const expectedPattern = new RegExp(`^workflow-with-import\\.usesHelper\\.${UUID_PATTERN}\\.pathkit-instrumented\\.ts$`);
    expect(fileName).toMatch(expectedPattern);
  });

  it('carries the generated-file banner and preserves the original code (plus scaffolding, from G3 onward)', () => {
    const instrumentedPath = writeInstrumentedCopy(fixturePath, 'usesHelper');
    writtenPaths.push(instrumentedPath);

    const instrumentedText = fs.readFileSync(instrumentedPath, 'utf8');

    expect(instrumentedText).toMatch(/^\/\/ AUTO-GENERATED by pathkit coverage/);
    // usesHelper has no if/else branches, but G3 onward always adds the
    // per-function trace/query scaffolding, so an exact byte-for-byte match
    // against the original (true only at G2) no longer holds — this asserts
    // the original statement is still present unchanged instead.
    expect(instrumentedText).toContain('return multiply(x, 2);');
  });

  it('preserves the relative import to a sibling helper module unchanged', () => {
    const instrumentedPath = writeInstrumentedCopy(fixturePath, 'usesHelper');
    writtenPaths.push(instrumentedPath);

    const instrumentedText = fs.readFileSync(instrumentedPath, 'utf8');
    expect(instrumentedText).toContain("from './helper'");
  });

  it('calling it twice in a row produces two distinct, non-colliding filenames', () => {
    const first = writeInstrumentedCopy(fixturePath, 'usesHelper');
    const second = writeInstrumentedCopy(fixturePath, 'usesHelper');
    writtenPaths.push(first, second);

    expect(first).not.toBe(second);
    expect(fs.existsSync(first)).toBe(true);
    expect(fs.existsSync(second)).toBe(true);
  });

  it('throws a PathKitError when the workflow file does not exist', () => {
    const missingPath = path.join(__dirname, 'fixtures', 'g2', 'does-not-exist.ts');
    expect(() => writeInstrumentedCopy(missingPath, 'whatever')).toThrow(/not found/i);
  });

  it('removeInstrumentedCopy deletes the file and does not throw if called again on an already-deleted path', () => {
    const instrumentedPath = writeInstrumentedCopy(fixturePath, 'usesHelper');
    removeInstrumentedCopy(instrumentedPath);
    expect(fs.existsSync(instrumentedPath)).toBe(false);
    expect(() => removeInstrumentedCopy(instrumentedPath)).not.toThrow();
  });
});

describe('prepareCoverageRun — G10 (Gap 2)', () => {
  const fixturePath = path.join(__dirname, 'fixtures', 'g2', 'workflow-with-import.ts');
  let cleanups: Array<() => void> = [];

  afterEach(() => {
    for (const cleanup of cleanups) cleanup();
    cleanups = [];
  });

  it('writes an instrumented copy and returns a cleanup() that removes it', () => {
    const { instrumentedFilePath, cleanup } = prepareCoverageRun(fixturePath, 'usesHelper');
    cleanups.push(cleanup);

    expect(fs.existsSync(instrumentedFilePath)).toBe(true);
    cleanup();
    expect(fs.existsSync(instrumentedFilePath)).toBe(false);
  });

  it("cleanup() is safe to call more than once (e.g. wired into both a test's own logic and afterEach)", () => {
    const { instrumentedFilePath, cleanup } = prepareCoverageRun(fixturePath, 'usesHelper');
    cleanup();
    expect(() => cleanup()).not.toThrow();
    expect(fs.existsSync(instrumentedFilePath)).toBe(false);
  });

  it('removes a stale instrumented copy left behind by a prior crashed run before writing a new one', () => {
    const dir = path.dirname(fixturePath);
    const staleFilePath = path.join(
      dir,
      'workflow-with-import.usesHelper.deadbeef-0000-0000-0000-000000000000.pathkit-instrumented.ts',
    );
    fs.writeFileSync(staleFilePath, '// stale leftover from a prior crashed run\n', 'utf8');

    try {
      expect(fs.existsSync(staleFilePath)).toBe(true);

      const { instrumentedFilePath, cleanup } = prepareCoverageRun(fixturePath, 'usesHelper');
      cleanups.push(cleanup);

      expect(fs.existsSync(staleFilePath)).toBe(false); // removed by the best-effort cleanup pass
      expect(fs.existsSync(instrumentedFilePath)).toBe(true); // the new run's own copy is unaffected
    } finally {
      fs.rmSync(staleFilePath, { force: true }); // in case the cleanup pass itself failed for some reason
    }
  });

  it('does not remove an instrumented copy belonging to a different function in the same directory', () => {
    const dir = path.dirname(fixturePath);
    const unrelatedFilePath = path.join(
      dir,
      'workflow-with-import.someOtherFunction.deadbeef-0000-0000-0000-000000000000.pathkit-instrumented.ts',
    );
    fs.writeFileSync(unrelatedFilePath, '// belongs to a different function\n', 'utf8');

    try {
      const { cleanup } = prepareCoverageRun(fixturePath, 'usesHelper');
      cleanups.push(cleanup);

      expect(fs.existsSync(unrelatedFilePath)).toBe(true);
    } finally {
      fs.rmSync(unrelatedFilePath, { force: true });
    }
  });
});
