import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import * as path from 'node:path';
import { PathKitError } from './errors';

const INSTRUMENTED_SUFFIX = 'pathkit-instrumented.ts';

/**
 * Writes an instrumented copy of a workflow file as a sibling of the
 * original — same directory, not a temp directory elsewhere — because
 * Temporal Worker's `workflowsPath` bundling resolves the workflow file's
 * own relative imports from its own on-disk location; writing the copy
 * anywhere else would break those imports (see LIMITATIONS.md).
 *
 * The generated filename is `<sourceName>.<functionName>.<uniqueId>.pathkit-instrumented.ts`:
 * the function name is included because coverage tracking is per-function
 * and a single file can export more than one workflow function, and
 * `uniqueId` is a full, untruncated `crypto.randomUUID()` so that parallel
 * test workers or repeated runs never collide on the same filename.
 *
 * At this milestone (G2) the copy's text is unmodified apart from a
 * generated-file banner comment — real tracking-call insertion is added in
 * later milestones (G3 onward).
 */
export function writeInstrumentedCopy(workflowFilePath: string, functionName: string): string {
  if (!existsSync(workflowFilePath)) {
    throw new PathKitError(`Workflow file not found: ${workflowFilePath}`);
  }

  const instrumentedFilePath = instrumentedFilePathFor(workflowFilePath, functionName);
  const originalText = readFileSync(workflowFilePath, 'utf8');
  const banner = generatedFileBanner(workflowFilePath, functionName);
  writeFileSync(instrumentedFilePath, banner + originalText, 'utf8');

  return instrumentedFilePath;
}

/** Deletes an instrumented copy. Never throws if the file is already gone. */
export function removeInstrumentedCopy(instrumentedFilePath: string): void {
  rmSync(instrumentedFilePath, { force: true });
}

function instrumentedFilePathFor(workflowFilePath: string, functionName: string): string {
  const dir = path.dirname(workflowFilePath);
  const sourceName = path.basename(workflowFilePath, path.extname(workflowFilePath));
  const uniqueId = randomUUID();
  return path.join(dir, `${sourceName}.${functionName}.${uniqueId}.${INSTRUMENTED_SUFFIX}`);
}

function generatedFileBanner(workflowFilePath: string, functionName: string): string {
  const sourceFileName = path.basename(workflowFilePath);
  return (
    `// AUTO-GENERATED by pathkit coverage — safe to delete, do not edit.\n` +
    `// Instrumented copy of ${sourceFileName} (function: ${functionName}).\n\n`
  );
}
