import { existsSync, rmSync, writeFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import * as path from 'node:path';
import { Node, SourceFile } from 'ts-morph';
import { PathKitError } from './errors';
import { buildWorkflowGraphWithNodeRefs, WorkflowGraph } from './graph';
import { parseWorkflowFile, WorkflowFunctionNode } from './parser';

const INSTRUMENTED_SUFFIX = 'pathkit-instrumented.ts';
const TEMPORAL_WORKFLOW_MODULE = '@temporalio/workflow';

/**
 * Writes an instrumented copy of a workflow file as a sibling of the
 * original — same directory, not a temp directory elsewhere — because
 * Temporal Worker's `workflowsPath` bundling resolves the workflow file's
 * own relative imports from its own on-disk location; writing the copy
 * anywhere else would break those imports (see LIMITATIONS.md).
 *
 * The generated filename is `<sourceName>.<functionName>.<uniqueId>.pathkit-instrumented.ts`:
 * the function name is included because coverage tracking is per-function
 * and a single file can export more than one workflow function, and
 * `uniqueId` is a full, untruncated `crypto.randomUUID()` so that parallel
 * test workers or repeated runs never collide on the same filename.
 *
 * As of G3, the copy gets real tracking instrumentation for if/else
 * decision points only (a per-function trace array, a namespaced Query
 * exposing it, and a `push()` call in each branch arm) — try/catch,
 * Promise.race/condition(), and retry-loop decision points are left
 * untouched until later milestones (G5–G7).
 */
export function writeInstrumentedCopy(workflowFilePath: string, functionName: string): string {
  if (!existsSync(workflowFilePath)) {
    throw new PathKitError(`Workflow file not found: ${workflowFilePath}`);
  }

  const parsed = parseWorkflowFile(workflowFilePath);
  const fn = parsed.find((f) => f.name === functionName);
  if (fn === undefined) {
    throw new PathKitError(`Workflow file ${workflowFilePath} has no exported function named ${functionName}`);
  }

  const originalText = fn.node.getSourceFile().getFullText();
  const instrumentedBody = instrumentText(originalText, fn.node, functionName);

  const instrumentedFilePath = instrumentedFilePathFor(workflowFilePath, functionName);
  const banner = generatedFileBanner(workflowFilePath, functionName);
  writeFileSync(instrumentedFilePath, banner + instrumentedBody, 'utf8');

  return instrumentedFilePath;
}

/** Deletes an instrumented copy. Never throws if the file is already gone. */
export function removeInstrumentedCopy(instrumentedFilePath: string): void {
  rmSync(instrumentedFilePath, { force: true });
}

function instrumentedFilePathFor(workflowFilePath: string, functionName: string): string {
  const dir = path.dirname(workflowFilePath);
  const sourceName = path.basename(workflowFilePath, path.extname(workflowFilePath));
  const uniqueId = randomUUID();
  return path.join(dir, `${sourceName}.${functionName}.${uniqueId}.${INSTRUMENTED_SUFFIX}`);
}

function generatedFileBanner(workflowFilePath: string, functionName: string): string {
  const sourceFileName = path.basename(workflowFilePath);
  return (
    `// AUTO-GENERATED by pathkit coverage — safe to delete, do not edit.\n` +
    `// Instrumented copy of ${sourceFileName} (function: ${functionName}).\n\n`
  );
}

/** A pending change to the original file's text, applied as plain string splicing (see `applyEdits`). */
interface TextEdit {
  start: number;
  end: number;
  text: string;
}

function instrumentText(originalText: string, fn: WorkflowFunctionNode, functionName: string): string {
  const sourceFile = fn.getSourceFile();
  const body = fn.getBody();
  if (body === undefined || !Node.isBlock(body)) {
    throw new PathKitError(
      `Cannot instrument function "${functionName}": it must have a block body ({ ... }) to be instrumented, ` +
        `not an implicit-return arrow function.`,
    );
  }

  const { graph, nodeAstRefs } = buildWorkflowGraphWithNodeRefs(fn, functionName);
  const traceVarName = `__pathkitTrace__${functionName}`;
  const queryVarName = `__pathkit_coverage__${functionName}`;

  const edits: TextEdit[] = [
    ...ifElseEdits(graph, nodeAstRefs, traceVarName),
    setHandlerEdit(body, traceVarName, queryVarName),
    ...scaffoldEdits(sourceFile, traceVarName, queryVarName),
  ];

  return applyEdits(originalText, edits);
}

/**
 * One edit per if/else arm (2 edits per if-decision node): a `push()` call
 * for the "true" edge as the first statement of the `then` arm, and one for
 * the "false" edge as the first statement of the `else` arm — synthesizing
 * an empty `else { ... }` if none exists. The edge index baked into each
 * push call is the literal position of that edge in `graph.edges`, which is
 * stable because a given if-decision node always has exactly one "true" and
 * one "false" edge in `graph.edges`, however deeply anything inside it (or
 * after it) is nested.
 */
function ifElseEdits(graph: WorkflowGraph, nodeAstRefs: Map<string, Node>, traceVarName: string): TextEdit[] {
  const edits: TextEdit[] = [];

  for (const node of graph.nodes) {
    if (node.kind !== 'decision') continue;
    const astNode = nodeAstRefs.get(node.id);
    if (astNode === undefined || !Node.isIfStatement(astNode)) continue; // a different decision kind, not this milestone's concern yet

    const trueEdge = graph.edges.find((e) => e.from === node.id && e.label === 'true');
    const falseEdge = graph.edges.find((e) => e.from === node.id && e.label === 'false');
    if (trueEdge === undefined || falseEdge === undefined) {
      throw new PathKitError(`Internal error: if-decision node ${node.id} is missing a true/false edge.`);
    }

    edits.push(armEdit(astNode.getThenStatement(), pushStatement(traceVarName, graph.edges.indexOf(trueEdge))));

    const elseStatement = astNode.getElseStatement();
    const falsePush = pushStatement(traceVarName, graph.edges.indexOf(falseEdge));
    if (elseStatement === undefined) {
      const pos = astNode.getThenStatement().getEnd();
      edits.push({ start: pos, end: pos, text: ` else { ${falsePush} }` });
    } else {
      edits.push(armEdit(elseStatement, falsePush));
    }
  }

  return edits;
}

/**
 * Inserts a push call as the first statement of an if/else arm. A `Block`
 * arm (`{ ... }`) gets the push inserted right after its opening brace. A
 * non-`Block` arm — a single bare statement (`if (x) return 'a';`), or a
 * nested `if` for an `else if (...)` chain — is wrapped in a new block
 * (`{ push(...); <original arm> }`), which is syntactically valid and
 * behaviorally identical to the original, uniformly covering both cases.
 */
function armEdit(arm: Node, pushText: string): TextEdit {
  if (Node.isBlock(arm)) {
    const pos = arm.getStart() + 1;
    return { start: pos, end: pos, text: ` ${pushText}` };
  }
  return { start: arm.getStart(), end: arm.getEnd(), text: `{ ${pushText} ${arm.getText()} }` };
}

function pushStatement(traceVarName: string, edgeIndex: number): string {
  return `${traceVarName}.push('${edgeIndex}');`;
}

/** Registers the coverage query as the very first statement of the function body. */
function setHandlerEdit(body: Node, traceVarName: string, queryVarName: string): TextEdit {
  const pos = body.getStart() + 1;
  return { start: pos, end: pos, text: ` setHandler(${queryVarName}, () => [...${traceVarName}]);` };
}

/**
 * Module-level scaffolding: the `defineQuery`/`setHandler` import (merged
 * into an existing `@temporalio/workflow` named import if present, else a
 * new import statement) and the per-function trace array + query
 * definition, inserted right after the last import (or at the top of the
 * file if there are none).
 */
function scaffoldEdits(sourceFile: SourceFile, traceVarName: string, queryVarName: string): TextEdit[] {
  const edits: TextEdit[] = [];
  const neededNamedImports = ['defineQuery', 'setHandler'];
  const moduleScaffoldText =
    `\nconst ${traceVarName}: string[] = [];\n` + `const ${queryVarName} = defineQuery<string[]>('${queryVarName}');\n`;

  const existingImport = sourceFile
    .getImportDeclarations()
    .find((d) => d.getModuleSpecifierValue() === TEMPORAL_WORKFLOW_MODULE);

  if (existingImport === undefined) {
    const importText = `import { ${neededNamedImports.join(', ')} } from '${TEMPORAL_WORKFLOW_MODULE}';\n`;
    edits.push({ start: 0, end: 0, text: importText + moduleScaffoldText });
    return edits;
  }

  const namedBindings = existingImport.getImportClause()?.getNamedBindings();
  if (namedBindings !== undefined && !Node.isNamedImports(namedBindings)) {
    throw new PathKitError(
      `Cannot instrument: the existing "${TEMPORAL_WORKFLOW_MODULE}" import doesn't use named imports ` +
        `(e.g. \`import * as workflow from '${TEMPORAL_WORKFLOW_MODULE}'\`), which isn't supported yet.`,
    );
  }

  const existingNames = new Set((namedBindings?.getElements() ?? []).map((el) => el.getName()));
  const missingNames = neededNamedImports.filter((n) => !existingNames.has(n));

  if (missingNames.length > 0) {
    if (namedBindings === undefined) {
      throw new PathKitError(
        `Cannot instrument: the existing "${TEMPORAL_WORKFLOW_MODULE}" import has no named imports to merge into ` +
          `(e.g. a bare \`import '${TEMPORAL_WORKFLOW_MODULE}'\`), which isn't supported yet.`,
      );
    }
    const pos = namedBindings.getEnd() - 1; // right before the closing `}`
    edits.push({ start: pos, end: pos, text: `, ${missingNames.join(', ')}` });
  }

  const scaffoldAnchor = existingImport.getEnd();
  edits.push({ start: scaffoldAnchor, end: scaffoldAnchor, text: moduleScaffoldText });

  return edits;
}

/** Applies edits by plain string splicing, in descending-position order so earlier offsets stay valid. */
function applyEdits(originalText: string, edits: TextEdit[]): string {
  const sorted = [...edits].sort((a, b) => b.start - a.start || b.end - a.end);
  let result = originalText;
  for (const edit of sorted) {
    result = result.slice(0, edit.start) + edit.text + result.slice(edit.end);
  }
  return result;
}
